// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LEGO Control",
    platforms: [
      .macOS(.v12),
      .iOS(.v16),
      .watchOS(.v9),
    ],
    products: [
      .library(name: "LEGOKit", targets: ["LEGOKit"]),
    ],
    targets: [
      .target(name: "LEGOKit"),
    ]
)
